version: '3.8'

volumes:
  db_data:

services:
    mongo:
        container_name: mongo
        image: mongo
        ports:
          - 27017:27017
        volumes:
          - db_data:/data/db
          - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        healthcheck:
          test: "[ `echo 'db.runCommand(\"ping\").ok' | mongo localhost/example-database --quiet` ] && echo 0 || echo 1"
          interval: 5s
          start_period: 10s
          timeout: 4s
          retries: 3

    api:
      container_name: api
      env_file:
        - .env
      build:
        context: ./
      command: npm run start:dev
      environment:
        PORT: 3000
        NODE_ENV: development
        MONGO_URL: mongo:27017
      links:
        - mongo
      ports:
        - 3000:3000
      depends_on:
        - mongo

