version: '3.8'

services:
    mongo:
        image: mongo:4.2.6
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
        restart: unless-stopped

    api:
        build:
            target: production
        command: node dist/src/app.js
        environment:
            NODE_ENV: production
            PORT: 3000
        restart: always
